# Generated by Django 4.1.7 on 2023-03-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_cart_product_create_at_order_cartproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
