# Generated by Django 4.1.7 on 2023-03-03 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_category_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('cancelled', 'cancelled')], max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'paystack'), ('transfer', 'transfer')], max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ref',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.cart'),
        ),
    ]
