# Generated by Django 4.1.7 on 2023-03-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_cart_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'paystack'), ('transfer', 'transfer')], default='paystack', max_length=225, null=True),
        ),
    ]
